---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-host
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      discovery.type: "single-node"
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#      ELASTIC_PASSWORD: password
#    extra_hosts:
#      - "moby:127.0.0.1"
#      - "localhost: 127.0.0.1"
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.1.1
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    extra_hosts:
#      - "moby:127.0.0.1"
#      - "localhost: 127.0.0.1"
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.1.1
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#    ports:
#      - "5000:5000"
#      - "9600:9600"
#    depends_on:
#      - elasticsearch
#      - kafka
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    extra_hosts:
#      - "moby:127.0.0.1"
#      - "localhost: 127.0.0.1"
